
import React, { useState, useEffect, useMemo } from 'react';
import { InventoryItem, ProductEntity, ServiceEntity, ProductionOrder } from '../types';
import { Save, Plus, Trash2, Factory, AlertCircle, ArrowRight } from 'lucide-react';

interface AvailableBatch {
  batchId: string;
  productName: string;
  productCode: string;
  supplier: string;
  supplierCode: string;
  unitCost: number;
  remainingQuantity: number;
  isService?: boolean;
}

interface ProcessFormProps {
  availableBatches: AvailableBatch[];
  registeredProducts: ProductEntity[];
  registeredServices: ServiceEntity[];
  onSave: (order: Omit<ProductionOrder, 'id'>) => void;
}

const ProcessForm: React.FC<ProcessFormProps> = ({ availableBatches, registeredProducts, registeredServices, onSave }) => {
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [selectedBatchId, setSelectedBatchId] = useState('');
  const [processedQuantity, setProcessedQuantity] = useState<number | ''>('');
  
  // Dynamic list of outputs
  const [outputs, setOutputs] = useState<{
    productId: string;
    quantity: number | '';
    isService: boolean; // Destination type
  }[]>([{ productId: '', quantity: '', isService: false }]);

  const [error, setError] = useState('');

  // Get source batch details
  const sourceBatch = useMemo(() => 
    availableBatches.find(b => b.batchId === selectedBatchId), 
  [selectedBatchId, availableBatches]);

  // Calculate Loss
  const loss = useMemo(() => {
    const input = Number(processedQuantity) || 0;
    const totalOutput = outputs.reduce((acc, curr) => acc + (Number(curr.quantity) || 0), 0);
    return input - totalOutput;
  }, [processedQuantity, outputs]);

  const handleAddOutput = () => {
    setOutputs(prev => [...prev, { productId: '', quantity: '', isService: false }]);
  };

  const handleRemoveOutput = (index: number) => {
    setOutputs(prev => prev.filter((_, i) => i !== index));
  };

  const handleOutputChange = (index: number, field: 'productId' | 'quantity' | 'isService', value: string | boolean) => {
    setOutputs(prev => {
      const newOutputs = [...prev];
      if (field === 'quantity') {
        newOutputs[index].quantity = parseFloat(value as string) || 0; 
      } else if (field === 'isService') {
         // If type changes, clear the product selection because the list changes
         newOutputs[index].isService = value as boolean;
         newOutputs[index].productId = ''; 
      } else {
        newOutputs[index].productId = value as string;
      }
      return newOutputs;
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!sourceBatch) {
      setError('Selecione um material de origem (Lote).');
      return;
    }

    if (!processedQuantity || Number(processedQuantity) <= 0) {
      setError('Informe a quantidade a ser processada.');
      return;
    }

    if (Number(processedQuantity) > sourceBatch.remainingQuantity) {
      setError(`Quantidade indisponível. Lote possui apenas ${sourceBatch.remainingQuantity} Kg.`);
      return;
    }

    // Validate outputs
    const validOutputs = outputs.filter(o => o.productId && Number(o.quantity) > 0);
    if (validOutputs.length === 0) {
      setError('Adicione pelo menos um material de saída (produto gerado).');
      return;
    }

    if (loss < 0) {
      setError('A soma das saídas não pode ser maior que a entrada.');
      return;
    }

    // Build the payload
    const finalOutputs = validOutputs.map(o => {
      // Find item in the correct list based on type
      const list = o.isService ? registeredServices : registeredProducts;
      const prod = list.find(p => p.id === o.productId);
      
      return {
        productName: prod?.name || 'Desconhecido',
        productCode: prod?.code || '000',
        quantity: Number(o.quantity),
        newBatchId: '', // Will be generated by parent
        destinationIsService: o.isService
      };
    });

    onSave({
      date,
      sourceBatchId: sourceBatch.batchId,
      sourceProduct: sourceBatch.productName,
      sourceIsService: !!sourceBatch.isService,
      processedQuantity: Number(processedQuantity),
      supplier: sourceBatch.supplier,
      supplierCode: sourceBatch.supplierCode,
      outputs: finalOutputs,
      loss
    });

    // Reset Form
    setSelectedBatchId('');
    setProcessedQuantity('');
    setOutputs([{ productId: '', quantity: '', isService: false }]);
    alert('Processo registrado e estoque atualizado com sucesso!');
  };

  const inputClass = "w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none text-gray-800 bg-white transition-all";

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <div className="flex items-center gap-3 mb-6">
        <div className="bg-emerald-900 p-3 rounded-xl text-white">
            <Factory size={24} />
        </div>
        <div>
            <h2 className="text-2xl font-bold text-emerald-900">Novo Processo</h2>
            <p className="text-sm text-gray-500">Transformação de estoque e geração de OPs</p>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-xl border border-gray-200 overflow-hidden">
        
        {/* Header */}
        <div className="bg-gray-50 p-6 border-b border-gray-200">
           <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">Data do Processo</label>
                <input 
                  type="date" 
                  value={date} 
                  onChange={(e) => setDate(e.target.value)} 
                  className={inputClass} 
                  required 
                />
              </div>
              <div className="md:col-span-2">
                {/* Changed Label as requested */}
                <label className="block text-sm font-bold text-gray-700 mb-2">Seleção de Material</label>
                <select 
                  value={selectedBatchId} 
                  onChange={(e) => setSelectedBatchId(e.target.value)}
                  className={inputClass}
                >
                  <option value="">-- Selecione um Lote para Processar --</option>
                  {availableBatches.map(b => (
                    <option key={b.batchId} value={b.batchId}>
                       {b.batchId} - {b.productName} ({b.isService ? 'M.O.' : 'Prod'}) - {b.remainingQuantity} Kg
                    </option>
                  ))}
                </select>
              </div>
           </div>
        </div>

        <form onSubmit={handleSubmit} className="p-6">
           {error && (
             <div className="bg-red-50 text-red-700 p-4 rounded-lg flex items-center gap-2 mb-6 border border-red-100">
               <AlertCircle size={20} />
               {error}
             </div>
           )}

           {/* Source Details */}
           <div className="bg-yellow-50 p-4 rounded-xl border border-yellow-200 mb-6 flex flex-col md:flex-row gap-6 items-center">
              <div className="flex-1 w-full">
                 <label className="block text-xs font-bold text-yellow-800 uppercase mb-1">Produto Selecionado</label>
                 <div className="font-bold text-gray-800 text-lg">{sourceBatch ? sourceBatch.productName : '---'}</div>
                 <div className="text-sm text-gray-500">
                     {sourceBatch ? `${sourceBatch.supplier} (${sourceBatch.supplierCode})` : '---'}
                     {sourceBatch?.isService && <span className="ml-2 bg-blue-100 text-blue-800 text-xs px-2 py-0.5 rounded font-bold">ESTOQUE M.O.</span>}
                 </div>
              </div>
              <div className="w-full md:w-48">
                 <label className="block text-xs font-bold text-yellow-800 uppercase mb-1">Qtd. Processada (Kg)</label>
                 <input 
                    type="number" 
                    value={processedQuantity} 
                    onChange={(e) => setProcessedQuantity(e.target.value === '' ? '' : parseFloat(e.target.value))} 
                    className="w-full p-2 border border-yellow-300 rounded focus:ring-2 focus:ring-yellow-500 outline-none text-xl font-bold text-center"
                    placeholder="0.00"
                 />
              </div>
           </div>

           <div className="flex justify-center mb-6">
              <ArrowRight className="text-gray-300 rotate-90 md:rotate-0" size={32} />
           </div>

           {/* Outputs */}
           <div className="space-y-4 mb-8">
              <h3 className="text-emerald-900 font-bold flex items-center gap-2">
                 Materiais Gerados (Saídas)
                 <span className="text-xs font-normal text-gray-500 bg-gray-100 px-2 py-1 rounded">Novos lotes serão gerados com o mesmo fornecedor</span>
              </h3>

              {outputs.map((output, index) => (
                <div key={index} className="flex flex-col md:flex-row gap-3 items-end bg-gray-50 p-4 rounded-lg border border-gray-100 animate-in fade-in slide-in-from-top-2 duration-300">
                    
                    {/* Destination Selection */}
                    <div className="w-full md:w-48">
                        <label className="block text-xs font-bold text-gray-600 mb-1">Destino</label>
                        <select 
                            value={output.isService ? 'service' : 'product'}
                            onChange={(e) => handleOutputChange(index, 'isService', e.target.value === 'service')}
                            className={`${inputClass} font-bold text-sm`}
                        >
                            <option value="product">Estoque Atual</option>
                            <option value="service">Estoque M.O.</option>
                        </select>
                    </div>

                    <div className="flex-1 w-full">
                        <label className="block text-xs font-bold text-gray-600 mb-1">Material {index + 1}</label>
                        <select 
                           value={output.productId} 
                           onChange={(e) => handleOutputChange(index, 'productId', e.target.value)}
                           className={inputClass}
                           required
                        >
                           <option value="">-- Selecione o Item --</option>
                           {/* Switch list based on destination type */}
                           {(output.isService ? registeredServices : registeredProducts).map(p => (
                             <option key={p.id} value={p.id}>{p.code} - {p.name}</option>
                           ))}
                        </select>
                    </div>

                    <div className="w-full md:w-40">
                        <label className="block text-xs font-bold text-gray-600 mb-1">Qtd (Kg)</label>
                        <input 
                           type="number" 
                           value={output.quantity}
                           onChange={(e) => handleOutputChange(index, 'quantity', e.target.value)}
                           className={inputClass}
                           placeholder="0.00"
                           required
                        />
                    </div>
                    <button 
                       type="button" 
                       onClick={() => handleRemoveOutput(index)}
                       className="p-3 bg-red-100 text-red-500 rounded-lg hover:bg-red-200 transition-colors"
                       title="Remover Item"
                       disabled={outputs.length === 1}
                    >
                       <Trash2 size={20} />
                    </button>
                </div>
              ))}

              <button 
                type="button" 
                onClick={handleAddOutput}
                className="text-sm font-bold text-emerald-700 flex items-center gap-1 hover:underline"
              >
                <Plus size={16} /> Adicionar Novo Material
              </button>
           </div>

           {/* Footer / Summary */}
           <div className="border-t border-gray-200 pt-6 flex flex-col md:flex-row justify-between items-center gap-6">
              <div className="flex items-center gap-6 text-sm">
                 <div className="flex flex-col">
                    <span className="text-gray-500 uppercase text-xs font-bold">Total Entrada</span>
                    <span className="font-mono font-bold text-lg">{Number(processedQuantity).toFixed(2)} Kg</span>
                 </div>
                 <div className="text-gray-300">|</div>
                 <div className="flex flex-col">
                    <span className="text-gray-500 uppercase text-xs font-bold">Total Saída</span>
                    <span className="font-mono font-bold text-lg text-emerald-600">
                       {(Number(processedQuantity) - loss).toFixed(2)} Kg
                    </span>
                 </div>
                 <div className="text-gray-300">|</div>
                 <div className="flex flex-col">
                    <span className="text-gray-500 uppercase text-xs font-bold">Perca (Perda)</span>
                    <span className={`font-mono font-bold text-lg ${loss < 0 ? 'text-red-500' : 'text-orange-500'}`}>
                       {loss.toFixed(2)} Kg
                    </span>
                 </div>
              </div>

              <button 
                type="submit" 
                className="bg-emerald-800 hover:bg-emerald-900 text-white font-bold py-3 px-8 rounded-xl shadow-lg flex items-center gap-2 transition-all transform hover:scale-105"
              >
                <Save size={20} />
                SALVAR PROCESSO
              </button>
           </div>

        </form>
      </div>
    </div>
  );
};

export default ProcessForm;